application: mailmypdf
version: 1
runtime: python27
api_version: 1
threadsafe: true

builtins:
- deferred: on
- remote_api: on

handlers:
- url: /static
  static_dir: static
  
- url: /(favicon\.ico|robots\.txt)
  static_files: static/\1
  upload: static/(.*)
  expiration: '1d'
  
- url: /.*
  script: mailmypdf.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest