application: mailmypdf
version: 1
runtime: python27
api_version: 1
threadsafe: true

builtins:
- deferred: on
- remote_api: on

handlers:
- url: /static
  static_dir: static
  
- url: /static/js
  static_dir: static/js
  
- url: /static/css
  static_dir: static/css
  
- url: /static/py
  static_dir: static/py
  
- url: /(favicon\.ico|robots\.txt)
  static_files: static/\1
  upload: static/(.*)
  expiration: '1m'
  
- url: /.*
  script: mailmypdf.application
  secure: always
  

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest